@startuml 08-DatabaseExpansion
left to right direction
skinparam packageStyle rectangle

actor "System Developer" as Dev

rectangle "Database Expansion" {
  Dev -- (Real Time Data Scraping)
  (Real Time Data Scraping) ..> (Implement Scraper) : includes
  (Real Time Data Scraping) ..> (Test Scraper in Controlled Environment) : includes
  (Real Time Data Scraping) ..> (Integrate Extracted Data into Platform) : includes
  (Real Time Data Scraping) ..> (Display Complemented Data) : includes
}

note right of (Real Time Data Scraping)
  This process involves a system developer
  implementing and testing a real-time scraper
  to integrate data from Econodata, augmenting
  the existing platform's database and presenting
  the enriched data effectively.
end note

@enduml
