# Generated by Django 4.1 on 2023-12-04 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cnpj", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresas",
            name="qualificacao_resposavel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="empresas",
                to="cnpj.qualificacoes",
            ),
        ),
        migrations.AlterField(
            model_name="socios",
            name="qualificacao_representante_legal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="socios_representante",
                to="cnpj.qualificacoes",
            ),
        ),
        migrations.AlterField(
            model_name="socios",
            name="qualificacao_socio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="socios",
                to="cnpj.qualificacoes",
            ),
        ),
    ]
